### ISSUE TITLE
pip Installation error

### ISSUE THREAD

**Issue by yokawasa** [yokawasa/azure-search-ta#1]
The following error occurs in installing azure-search-ta-0.2.1 via pip

```
 pip install azure-search-ta
Collecting azure-search-ta
  Using cached azure-search-ta-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3owa_7nm/azure-search-ta/setup.py", line 12, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/home/yoichika/.virtualenvs/py3.5/lib/python3.5/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
```

**Comment by yokawasa** [comment]
Resolved at Release version 0.2.2
https://github.com/yokawasa/azure-search-ta/releases/tag/0.2.2
